<?php
/**
* @version 1.1.x
* @package nBill
* @copyright (C) 2006-2007 Netshine Software Limited
* @license Commercial
* 
* PLEASE NOTE: This is NOT free software. You must purchase a license in order to use this component.
* For more information, see www.nbill.co.uk
*
* All Rights Reserved. You may make amendments to any unencrypted files for your own use only or
* for the use of your customers if you are a website developer. HOWEVER, you are not permitted to
* re-distribute or re-sell this software in any form without the express permission of the copyright 
* holder. This software is NOT open source.
*
* This component was developed by Netshine Software Limited (www.netshinesoftware.com). Use of this
* software is entirely at your own risk.
*/

/** ensure this file is being included by a parent file */
defined( '_VALID_MOS' ) or die( 'Direct Access to this location is not allowed.' );

//Payment Gateway
define("INV_AUTO_GENERATED_INCOME", "Auto Generated by Payment Gateway.");
define("INV_GATEWAY_ERROR", INV_BRANDING_NAME . " Error Report");
define("INV_ERR_RECEIPT_NOT_PROCESSED", "A receipt notification for %s was received, but could not be processed because it could not be matched with an existing order or invoice. If you use " . INV_BRANDING_NAME . " to reconcile all of your transactions, you may need to add the income item manually.");
define("INV_GATEWAY_TITLE", "Payment Gateways");
define("INV_GATEWAY_INTRO", "Payment gateways are to allow you to use an online payment service provider to accept credit card payments. In order to add online payment features to your order forms, you will need a payment gateway extension specifically built for " . INV_BRANDING_NAME . " and your payment service provider. For details of payment gateway extensions that are currently available, please refer to the " . INV_BRANDING_NAME . " Website (%s).");
define("INV_GATEWAY_NAME", "Gateway Name");
define("INV_GATEWAY_DESCRIPTION", "Description");
define("INV_EDIT_GATEWAY", "Edit Gateway Settings");
define("INV_ERR_GATEWAY_PROBLEM", "There is a problem with this payment gateway. The action you requested could not be performed.");
define("INV_GATEWAY_SETTINGS", "Payment Gateway Settings");
define("INV_CONFIRM_UNINSTALL_GATEWAY", "WARNING! This will completely uninstall this payment gateway!");
define("INV_ERR_GATEWAY_NOT_REMOVED", "WARNING! Although the payment gateway has been deleted from " . INV_BRANDING_NAME . ", not all of the related files could be deleted.");
define("INV_ERR_GATEWAY_NOT_FOUND", "ERROR: The payment gateway associated with this order form or invoice could not be found. It will not be possible to pay online at the present time.");
define("INV_GATEWAY_WARNING", INV_BRANDING_NAME . " Warning Report");
define("INV_GATEWAY_ERR_ORDER_NOT_FOUND", "Pending Order ID '%s' not found");
define("INV_GATEWAY_INSTALL_WARNING", "WARNING! Only install payment gateways from trusted sources. A gateway script can access your entire website!");
define("INV_GATEWAY_CALLBACK_INFO", "The following information shows the contents of the \$_REQUEST and \$_SERVER PHP variables. A technician may find this information useful in determining why the error occurred.\n\n");
define("INV_GATEWAY_FILES_MISSING", "WARNING! The database tables for gateway '%s' are present in the database, but the gateway files are missing. This may be because you have upgraded " . INV_BRANDING_NAME . ". Please either re-install this payment gateway by clicking on the 'New' toolbar button above (your settings will be preserved), or delete it (which will permanently destroy all traces of this gateway).");
define("INV_GATEWAY_ERR", "A problem occurred whilst attempting to process your payment. The following error was returned: %s<br /><br />Please contact us if you need assistance.");
define("INV_GATEWAY_SUCCESS", "Thank you - your payment was received successfully.");
define("INV_GATEWAY_ERR_AMOUNT_MISMATCH", "ERROR - Amount mismatch (the amount received was different to the amount expected). Amount expected: %s; Amount received: %s");
define("INV_GATEWAY_ERR_DUPLICATE_NOTIFICATION", "ERROR - Duplicate notification of payment.");


/**************/
/* Version 1.1.4
/* Note to translators: Text amended for INV_GATEWAY_ERR (line 42 in the English file).
/**************/

//Version 1.2.0
define("INV_GATEWAY_DISPLAY_NAME", "Display Name");
define("INV_GATEWAY_PUBLISHED", "Published?");
define("INV_INSTR_GATEWAY_DISPLAY_NAME", "Used in a dropdown list for allowing user to select a gateway when renewing an order or paying an invoice. Note: When user selects a gateway on an order form, you must specify the display name to use in the field options. This setting is only for occasions when payments are made without using an order form.");
define("INV_INSTR_GATEWAY_PUBLISHED", "Whether or not this gateway should appear in a dropdown list for allowing a user to select a gateway. Note: This only applies to selection of a gateway when not using an order form. On an order form, you have to manually define which gateways are allowed, so this setting makes no difference there (ie. you can still use a gateway on an order form even if it is not published, but it cannot be used for paying an invoice or renewing an order unless it is published).");
?>
