tinyMCE.addI18n({'nb':{'dlg':{
modified:'Endret',
file:'Fil',
folder:'Mappe',
files:'filer',
folders:'mapper',
comments:'Kommentarer',
size:'Størrelse',
preview:'Forhåndsvisning',
duration:'Varighet',
dimensions:'Dimensjoner',
contents:'Innhold',
unwritable:'Kan ikke skrives til',
bad_name:'Feil i fil/mappe -navn',
message_tree:'Lager tre-liste …',
message_load:'Laster inn …',
message_properties:'Henter instillinger …',
current_dir:'Mappen du står i er: ',
help:'Hjelp',
name:'Navn',
'options':'Valg',
'confirm':'Bekreft',
yes:'Ja',
no:'Nei',
'alert':'Alarm',
folder_new:'Ny mappe',
rename:'Gi nytt navn',
'delete':'Slett',
save :'Lagre',
delete_item_alert:'Slett valgte element?',
rename_folder:'Gi nytt navn til mappen',
rename_file:'Gi nytt navn til filen',
rename_item_alert:'Endring av navn på filer/mapper vil bryte eksisterende lenker. Vil du fortsette?',
rename_item_name_new:'Oppgi et nytt navn på fil/mappe',
file_select:'Klikk på et filnavn for å legge til, klikk til høyre for filnavnet for å se filens attributter. CTRL+Click for å velge flere filer.',
notwritable:'Ikke skrivbar',
notwritable_desc:'Ikke skrivbar: Mappe eller fil er ikke skrivbar og kan derfor ikke gis nytt navn, flyttes eller slettes.',
bad_name: 'Feil fil- eller mappenavn',
bad_name_desc:'Feil i filnavn eller mappenavn. Unngå spesialtegn i navn på filer og mapper, også tegn som æ, ø og å. kun tegnene a-zA-Z0-9_-. kan inngå i navnene',
select_value:'Legg til verdi',
select_label:'Legg til verdi',
size_bytes:'Byte',
size_kb:'KB',
size_mb:'MB',
date_format:'',
media_not_supported:'Mediatype er ikke støttet av denne nettleseren',
one_of_many:'%o av %m',
element_selection:'Elementvalg',
uploading:'Laster opp …',
upload:'Last opp',
queue:'Legg i kø',
upload_drop:'Dra og slipp filene her',
cancel:'Avbryt',
ok:'OK',
browse:'Bla gjennom',
file_extension_error :'Filtype er ikke støttet',
file_size_error:'Filstørrelse overskrider maksimalt tillatt størrelse',
file_invalid_error:'Ugyldig filtype',
upload_drop:'Slipp filer her',
close:'Lukk',
'-600':'%f (%s) overskrider maksimalt tillatt størrelse på %m',
'-601':'Fil: %s',
'-800':'Fil: %s'
},
'pagebreak_dlg':{
desc:"Sett inn/endre sideskift",
title:"Sidetittel",
alias:"Alias for innholdsfortegnelse"
},
'imgmanager_dlg':{
missing_alt:"Er du sikker på at du vil fortsette uten å inkludere en alternativ tekst for bildet? Uten dette vil kanskje ikke bildet være tilgjengelig for brukere med handikapp, eller for dem som bruker tekstlesere, eller som surfer nettet med bilder avslått.",
no_src:'En nettadresse er påkrevd. Du må velge et bilde eller fylle inn en nettadresse.'
},
'link_dlg':{
is_email:"Nettadressen du fylte inn ser ut til å være en e-postadresse, vil du legge til påkrevd mailto:-prefiks?",
is_external:"Nettadressen du fylte inn ser ut til å være en ekstern lenke, vil du legge til påkrevd http://-prefiks?",
no_href:"En nettadresse er påkrevd. Du må velge en lenke eller fylle inn en nettadresse",
no_text:"Fyll inn en tekst for lenken",
email:"Opprett e-postadresse",
to:"Til",
cc:"Kopi",
bcc:"Blindkopi",
subject:"Emne",
invalid_email:" er ikke en gyldig e-postadresse!"
}
}});