// nb = Norwegian (bokmål) lang variables by Knut B. Jacobsen
// Klargjort for Joomla 1.1 av Jens-Christian Skibakk (jens.christian@start.no), http://www.joomlainorge.no

// Ferdig oversatt, 31. mars 2006

tinyMCE.addToLang('table',{
general_tab : 'Generelt',
advanced_tab : 'Avansert',
general_props : 'Generelle egenskaper',
advanced_props : 'Avanserte egenskaper',
desc : 'Opprett/endre tabell',
row_before_desc : 'Opprett rad over',
row_after_desc : 'Opprett rad under',
delete_row_desc : 'Fjern rad',
col_before_desc : 'Opprett kolonne foran',
col_after_desc : 'Opprett kolonne etter',
delete_col_desc : 'Fjern kolonne',
rowtype : 'Rad i tabell',
title : 'Opprett/endre tabell',
width : 'Bredde',
height : 'Høyde',
cols : 'Kolonner',
rows : 'Rader',
cellspacing : 'Cellemellomrom',
cellpadding : 'Cellefylling',
border : 'Ramme',
align : 'Justering',
align_default : 'Ingen',
align_left : 'Venstre',
align_right : 'Høyre',
align_middle : 'Midtstilt',
row_title : 'Rad-egenskaper',
cell_title : 'Celle-egenskaper',
cell_type : 'Celletype',
row_desc : 'Rad-egenskaper',
cell_desc : 'Celle-egenskaper',
valign : 'Vertikal justering',
align_top : 'Topp',
align_bottom : 'Bunn',
props_desc : 'Tabellegenskaper',
bordercolor : 'Rammefarge',
bgcolor : 'Bakgrunnsfarge',
merge_cells_title : 'Slå sammen tabellceller',
split_cells_desc : 'Splitt tabellceller',
merge_cells_desc : 'Slå sammen tabellceller',
cut_row_desc : 'Fjern tabellrad',
copy_row_desc : 'Kopier tabellrad',
paste_row_before_desc : 'Lim inn tabellrad foran',
paste_row_after_desc : 'Lim inn tabellrad etter',
id : 'Id',
style: 'Stil',
langdir : 'Språkretning',
langcode : 'Språkkode',
mime : 'Målets MIME type',
ltr : 'Venstre mot høyre',
rtl : 'Høyre mot venstre',
bgimage : 'Bakgrunnsbilde',
summary : 'Sammendrag',
td : "Data",
th : "Overskrift",
cell_cell : 'Oppdater valgt celle',
cell_row : 'Oppdater alle celler i raden',
cell_all : 'Oppdater alle celler i tabellen',
row_row : 'Oppdater valgt rad',
row_odd : 'Oppdater ulike rader i tabellen',
row_even : 'Oppdater like rader i tabellen',
row_all : 'Oppdater alle rader i tabellen',
thead : 'Tabellhode',
tbody : 'Tabellkropp',
tfoot : 'Tabellfot',
del : 'Slett tabell',
scope : 'Hensikt',
row : 'Rad',
col : 'Kolonne',
rowgroup : 'Radgruppe',
colgroup : 'Kolonnegruppe',
missing_scope: 'Er du sikker på at du vil fortsette uten å oppgi hensikten med denne tabellens hodecelle.'
});