tinyMCE.addI18n('nb.emotions_dlg',{
title:"Sett inn uttryksikon",
desc:"Uttrykksikoner",
confused:"Usikker",
cool:"Kul",
cry:"Gråter",
eek:"Hva i ...",
embarassed:"Flau"
evil:"Ond",
frown:"Skuffet",
grin:"Grimase",
laughing:"Ler",
mad:"Sint",
neutral:"Nøytral",
roll:"Ruller øyne",
sad:"Trist",
smile:"Smiler",
surprised:"Overrasket",
tongue_out:"Rekker tunge",
wink:"Blunker",
yell:"Roper",
});
