// nb Norwegian (bokmal) lang variables by Knut B. Jacobsen
// Klargjort for Joomla 1.1 av Jens-Christian Skibakk (jens.christian@start.no), http://www.joomlainorge.no

// Ferdig oversatt, 31. mars 2006

tinyMCE.addToLang('',{
theme_style_select : '--Stiler--',
theme_code_desc : 'Redigere HTML koden',
theme_code_title : 'HTML kildekode redigering',
theme_code_wordwrap : 'Ord deling',
theme_sub_desc : 'Nedsenket skrift',
theme_sup_desc : 'Opphøyd skrift',
theme_hr_desc : 'Sett inn horisontal linje',
theme_removeformat_desc : 'Fjern formatering',
theme_custom1_desc : 'Din spesialfunksjons beskrivelse her',
insert_image_border : 'Ramme',
insert_image_dimensions : 'Dimensjoner',
insert_image_vspace : 'Vertikalt tomrom',
insert_image_hspace : 'Horisontalt tomrom',
insert_image_align : 'Justering',
insert_image_align_default : 'Intet',
insert_image_align_baseline : 'Bunnlinjen',
insert_image_align_top : 'Lengst opp',
insert_image_align_middle : 'Midten',
insert_image_align_bottom : 'Lengst ned',
insert_image_align_texttop : 'Teksttopp',
insert_image_align_absmiddle : 'Absolutt midten',
insert_image_align_absbottom : 'Absolutt bunn',
insert_image_align_left : 'Venstre',
insert_image_align_right : 'Høyre',
theme_font_size : '-- Skriftstørrelse --',
theme_fontdefault : '-- Skriftfamilie --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraf',
theme_div : 'Div',
theme_address : 'Adresse',
theme_pre : 'Pre-formattert',
theme_h1 : 'Overskrift 1',
theme_h2 : 'Overskrift 2',
theme_h3 : 'Overskrift 3',
theme_h4 : 'Overskrift 4',
theme_h5 : 'Overskrift 5',
theme_h6 : 'Overskrift 6',
theme_colorpicker_title : 'Velg en farge',
theme_colorpicker_apply : 'Bruk',
theme_forecolor_desc : 'Velg forgrunnsfarge',
theme_backcolor_desc : 'Velg bakgrunnsfarge',
theme_charmap_title : 'Velg spesialtegn',
theme_charmap_desc : 'Sett inn spesialtegn',
theme_visualaid_desc : 'Slå av/på usynlige elementer',
insert_anchor_title : 'Opprette/endre anker',
insert_anchor_name : 'Ankernavn',
theme_anchor_desc : 'Opprette/endre anker',
theme_insert_link_titlefield : 'Tittel',
theme_clipboard_msg : 'Kopier/Klipp ut/Lim inn er ikke tilgjengelig i Mozilla/Firefox.\nVil du ha mere informasjon om dette?',
theme_path : 'Søkevei',
cut_desc : 'Klipp ut',
copy_desc : 'Kopier',
paste_desc : 'Lim inn',
link_list : 'Lenkeliste',
image_list : 'Bildeliste',
browse : 'Bla gjennom',
image_props_desc : 'Bildeegenskaper',
newdocument_desc : 'Nytt dokument',
class_name : 'Stil',
newdocument : 'Er du sikker på at du vil tømme hele redigeringsområdet?',
about_title : 'Om TinyMCE',
about : 'Om',
license : 'Lisens',
plugins : 'Programtillegg',
plugin : 'Programtillegg',
author : 'Utviklere',
version : 'Versjon',
loaded_plugins : 'Lastet programtillegg',
help : 'Hjelp',
not_set : '-- Ikke satt --',
close : 'Lukk',
toolbar_focus : 'Hopp til verktøylinje - Alt+Q, hopp til teksbehandler - Alt+Z , hopp til elementsti - Alt+X'
});
