tinyMCE.addI18n('en.style_dlg',{
title:"Endre css-stil",
apply:"Påfør endringer",
text_tab:"Tekst",
background_tab:"Bakgrunn",
block_tab:"Blokk",
box_tab:"Boks",
border_tab:"Kantlinjer",
list_tab:"Liste",
positioning_tab:"Posisjonering",
text_props:"Tekst",
text_font:"Font",
text_size:"Størrelse",
text_weight:"Vekt",
text_style:"Stil",
text_variant:"Variant",
text_lineheight:"Linje høyde",
text_case:"Versal",
text_color:"Farge",
text_decoration:"Dekor",
text_overline:"overstreket",
text_underline:"understreket",
text_striketrough:"gjennomstreket",
text_blink:"blinkende",
text_none:"ingen",
background_color:"Bakgrunnsfarge",
background_image:"Bakgrunnsbilde",
background_repeat:"Gjenta",
background_attachment:"Vedlegg",
background_hpos:"Horisontal plassering",
background_vpos:"Vertikal plassering",
block_wordspacing:"Mellomrom mellom ord",
block_letterspacing:"Mellomrom mellom bokstaver",
block_vertical_alignment:"Vertikal posisjonering",
block_text_align:"Tekst-posisjonering",
block_text_indent:"Tekst-indentering",
block_whitespace:"Mellomrom",
block_display:"Vis",
box_width:"Bredde",
box_height:"Høyde",
box_float:"Flyt",
box_clear:"Klarèr",
padding:"Kantavstand",
same:"Samme for alle",
top:"Øverst",
right:"Høyre",
bottom:"Nederst",
left:"Venstre",
margin:"Marg",
style:"Stil",
width:"Bredde",
height:"Høyde",
color:"Farge",
list_type:"Type",
bullet_image:"Bilde for punkt",
position:"Posisjon",
positioning_type:"Type",
visibility:"Synlighet",
zindex:"Z-indeks",
overflow:"Overflyt",
placement:"Plassering",
clip:"Klipp"
});
