tinyMCE.addI18n('no.dlg',{
// JCE specific
modified: 'Endret',
file: 'Fil',
folder: 'Mappe',
files: 'filer',
folders: 'mapper',
comments: 'Kommentarer',
size: 'Størrelse',
preview: 'Forhåndsvisning',
duration: 'Varighet',
dimensions: 'Dimensjoner',
contents: 'Innhold',
unwritable: 'Kan ikke skrives til',
bad_name: 'Feil i fil/mappe -navn',
message_tree: 'Lager tre-liste …',
message_load: 'Laster inn …',
message_properties: 'Henter instillinger …',
current_dir: 'Mappen du står i er: ',
help: 'Hjelp',
name: 'Navn',
'options': 'Valg',
'confirm': 'Bekreft',
yes: 'Ja',
no: 'Nei',
'alert': 'Alarm',
folder_new: 'Ny mappe',
rename: 'Gi nytt navn',
'delete': 'Slett',
delete_item_alert: 'Slett valgte element?',
rename_folder: 'Gi nytt navn til mappen',
rename_file: 'Gi nytt navn til filen',
rename_item_alert: 'Renaming files/folders will break existing links. Continue?',
file_select: 'Klikk på et filnavn for å legge til, klikk til høyre for filnavnet for å se filens attributter. CTRL+Click for å velge flere filer.',
notwritable: 'Ikke skrivbar',
notwritable_desc: 'Ikke skrivbar: Mappe eller fil er ikke skrivbar og kan derfor ikke gis nytt navn, flyttes eller slettes.',
bad_name: 'Feil fil- eller mappenavn',
bad_name_desc: 'Feil i filnavn eller mappenavn. Unngå spesialtegn i navn på filer og mapper, også tegn som æ, ø og å. kun tegnene a-zA-Z0-9_-. kan inngå i navnene',
select_value: 'Legg til verdi',
select_label: 'Legg til verdi',
size_bytes : 'Byte',
size_kb : 'KB',
size_mb : 'MB',
date_format : '',
media_not_supported:'Mediatype er ikke støttet av denne nettleseren',
one_of_many : '%o av %m',
element_selection : 'Elementvalg',
/**
 * Upload
 */
uploading: 'Laster opp …',
upload: 'Last opp',
queue: 'Legg i kø',
upload_exits: 'Om filen allerede finnes: ',
overwrite: 'Overskriv duplikatfiler',
upload_drop: 'Dra og slipp filene her',
file_exists_alert: 'En fil med samme navn finnes allerede i målmappen. Gi filen i køen et nytt navn, eller velg "Opprett unikt filnavn" fra "Om filen allerede finnes"-listen.',
unique: 'Opprett unikt filnavn',
cancel: 'Avbryt',
ok: 'OK',
browse: 'Bla',
file_extension_error : 'Filtype er ikke støttet',
file_size_error : 'Filstørrelse overskrider maksimalt tillatt størrelse',
file_invalid_error : 'Ugyldig filtype',
add : 'Legg til filer',
clear : 'Tøm kø',
upload_drop : 'Slipp filer her',
/**
 * Upload Error Codes
 */
'-600' : '%f (%s) overskrider maksimalt tillatt størrelse på %m',
'-601' : 'Fil: %s',
'-800' : 'Fil: %s'
});
