tinyMCE.addI18n('nb.imgmanager_ext_dlg',{
missing_alt: "Er du sikker på at du vil fortsette uten å inkludere en alternativ tekst for bildet? Uten dette vil kanskje ikke bildet være tilgjengelig for brukere med handikapp, eller for dem som bruker tekstlesere, eller som surfer nettet med bilder avslått.",
delta_width: 0,
delta_height: 0,
'0':'Original',
'-90': '90&deg; CW',
'90': '90&deg; CCW',
'180': '180&deg;',
'vertical': 'Vend vertikalt',
'horizontal': 'Vend horisontalt',
'view_images': 'Minityrbildevisning',
'view_list': 'Listevisning',
'use_thumbnail': 'Bruk assosiert miniatyrbilde for sprettopplenke?',
'resize': 'Endre størrelse',
'rotate': 'Roter',
'proportional': 'Proporsjonalt',
'cropped': 'Kuttet',
'mode': 'Modus',
'quality': 'Kvalitet',
'size': 'Størrelse',
'thumbnail': 'Miniatyrbilde',
'transform': 'Transform',
'width': 'Bredde',
'height': 'Høyde',
'create_thumbnail': 'Opprett miniatyrbilde',
'delete_thumbnail': 'Slett miniatyrbilde?',
'message_images': 'Klikk på et bilde for å vise egenskaper, dobbeltklikk for å sette det inn. CTRL + klikk for å velge flere bilder.',
'message_list': 'Klikk på et bildenavn for å sette inn, klikker til høyre for navnet for å vise egenskaper. CTRL + klikk  for å velge flere bilder.',
'no_src': 'Velg et bilde eller oppgi et bilde nettadressen.',
'no_popup_src' : 'Skriv inn en nettadresse til sprettoppbilde',
'upload_resize_tip' : 'Endre størrelse:Endre størrelse på de opplastede bildene til å passe innenfor den angitte bredden og høyden samtidig som størrelsesforholdet til originalbildet beholdes.',
'upload_thumbnail_tip' : 'Miniatyrbild::Lag et miniatyrbilde av det opplastede bilde ved hjelp av de angitte dimensjonene, beskjær miniatyrbilde dynamisk til passe innenfor disse dimensjonene om nødvendig.',
'upload_thumbnail_crop':'Beskjær til å passe',
'upload_thumbnail_crop_tip':'Beskjær til å passe::Miniatyrbilder vil bli beskåret for å passe til dimensjonene',
'greyscale' : 'Gråskala',
'sepia'	: ' Sepia',
'invert' : 'Negativ',
'lighten' : 'Gjør lysere',
'darken' : 'Gjør mørkere',
'saturate' : 'Boost',
'desaturate' : 'Fade',
'threshold' : 'Svarthvit',
'halftone' : 'Tegneserie',
'create_thumbnail_failed':'Kunne ikke opprette minityrbilde'
});
