tinyMCE.addI18n('nb.table_dlg',{
"rules_border":"ramme",
"rules_box":"boks",
"rules_vsides":"vsides",
"rules_rhs":"rhs",
"rules_lhs":"lhs",
"rules_hsides":"hsider",
"rules_below":"under",
"rules_above":"over",
"rules_void":"ingen",
rules:"Streker",
"frame_all":"alle",
"frame_cols":"kolonner",
"frame_rows":"rader",
"frame_groups":"grupper",
"frame_none":"ingen",
frame:"Ramme",
caption:"Tabelloverskrift",
"missing_scope":"Er du sikker på at du vil fortsette uten å angi et område for denne overskrifscellen? Uten dette kan det bli vanskelig for enkelte funksjonshemmede brukere å forstå innholdet eller dataene som blir presentert i tabellen.",
"cell_limit":"Du har overskredet maksimalt antall celler på {$cells}.",
"row_limit":"Du har overskredet maksimalt antall rader på {$rows}.",
"col_limit":"Du har overskredet maksimalt antall kolonner på {$cols}.",
colgroup:"Kolonnegruppe",
rowgroup:"Radgruppe",
scope:"Område",
tfoot:"Tabellfot",
tbody:"Tabellkropp",
thead:"Tabellhode",
"row_all":"Oppdater alle rader",
"row_even":"Oppdater partallsrader",
"row_odd":"Oppdater oddetallsrader",
"row_row":"Oppdater aktuell rad",
"cell_all":"Oppdater alle celler i tabellen",
"cell_row":"Oppdater alle celler i raden",
"cell_cell":"Oppdater aktuell celle",
th:"Overskrift",
td:"Data",
summary:"Sammendrag",
bgimage:"Bakgrunnsbilde",
rtl:"Høyre  mot venstre",
ltr:"Venstre mot høyre",
mime:"Målets MIME-type",
langcode:"Språkkode",
langdir:"Skriftretning",
style:"Stil",
id:"Id",
"merge_cells_title":"Slå sammen celler",
bgcolor:"Bakgrunn",
bordercolor:"Rammefarge",
"align_bottom":"Bunn",
"align_top":"Topp",
valign:"Vertikal justering",
"cell_type":"Celletype",
"cell_title":"Celleegenskaper",
"row_title":"Radegenskaper",
"align_middle":"Midtstilt",
"align_right":"Høyre",
"align_left":"Venstre",
"align_default":"Standard",
align:"Justering",
border:"Ramme",
cellpadding:"Cellefylling",
cellspacing:"Celleavstand",
rows:"Rader",
cols:"Kolonner",
height:"Høyde",
width:"Bredde",
title:"Sett inn / rediger tabell",
rowtype:"Rad i tabell",
"advanced_props":"Generelle egenskaper",
"general_props":"Generelt",
"advanced_tab":"Avansert",
"general_tab":"Generelt",
"cell_col":"Oppdater alle celler i kolonnen"
});
