tinyMCE.addI18n('nb.table_dlg',{
general_tab:"Generelt",
advanced_tab:"Avansert",
general_props:"Generelle egenskaper",
advanced_props:"Avanserte egenskaper",
rowtype:"Rad i tabelldel",
title:"Sett inn/Endre tabell",
width:"Bredde",
height:"Høyde",
cols:"Kolonner",
rows:"Rader",
cellspacing:"Celle-mellomrom",
cellpadding:"Celle-fyll",
border:"Ramme",
align:"Plassering",
align_default:"Standard",
align_left:"Venstre",
align_right:"Høyre",
align_middle:"Sentrert",
row_title:"Egenskaper for tabellrad",
cell_title:"Egenskaper for tabellcelle",
cell_type:"Celletype",
valign:"Vertikalplassering",
align_top:"Øverst",
align_bottom:"Nederst",
bordercolor:"Kantfarge",
bgcolor:"Bakgrunnsfarge",
merge_cells_title:"Slå sammen tabellceller",
id:"Id",
style:"Stil",
langdir:"Språkretning",
langcode:"Språkkode",
mime:"MIME-type for mål",
ltr:"Venstre til høyre",
rtl:"Høyre til venstre",
bgimage:"Bakgrunnsbilde",
summary:"Oppsumering",
td:"Data",
th:"Tittel",
cell_cell:"Oppdater valgt celle",
cell_row:"Oppdater alle seller i rad",
cell_all:"Oppdater alle celler i tabell",
row_row:"Oppdater valgt rad",
row_odd:"Oppdater oddetall-rader i tabell",
row_even:"Oppdater partall-rader i tabell",
row_all:"Oppdater alle rader i tabell",
thead:"Tabellhode",
tbody:"Tabellkropp",
tfoot:"Tabellfot",
scope:"Omfang",
rowgroup:"Radgruppe",
colgroup:"Kolonnegruppe",
col_limit:"Du har overskredet maksimalt antall kolonner {$cols}.",
row_limit:"Du har overskredet maksimalt antall rader {$rows}.",
cell_limit:"Du har overskredet maksimalt antall celler {$cells}.",
missing_scope:"Er du sikker på at du vil fortsette uten å spesifisere et omfang for denne tabellhode-cellen? Uten dette vil det kunne være vanskelig for brukere med handikap å forstå innhold eller data i tabellen.",
caption:"Tabelltekst",
frame:"Ramme",
frame_none:"ingen",
frame_groups:"grupper",
frame_rows:"rader",
frame_cols:"kolonner",
frame_all:"alle",
rules:"Regler",
rules_void:"tom",
rules_above:"over",
rules_below:"under",
rules_hsides:"hsider",
rules_lhs:"vhs",
rules_rhs:"hhs",
rules_vsides:"vsider",
rules_box:"boks",
rules_border:"kantlinje"
});
