// version 1.5.x $Id: nb.js 179 2007-02-14 19:24:38Z jens $
// author Joomla! i Norge http://www.joomlainorge.no oversettelser@joomlainorge.no
// copyright Copyright (C) 2005 - 2006 Joomla! i Norge. All rights reserved.
// license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php

tinyMCE.addToLang('',{
theme_style_select : '-- Stiler --',
theme_code_desc : 'Redigere HTM-koden',
theme_code_title : 'HTML-kildekode redigering',
theme_code_wordwrap : 'Orddeling',
theme_sub_desc : 'Nedsenket skrift',
theme_sup_desc : 'Opphøyd skrift',
theme_hr_desc : 'Sett inn horisontal linje',
theme_removeformat_desc : 'Fjern formatering',
theme_custom1_desc : 'Din beskrivelse av spesialfunksjonen her',
insert_image_border : 'Ramme',
insert_image_dimensions : 'Dimensjoner',
insert_image_vspace : 'Vertikalt tomrom',
insert_image_hspace : 'Horisontalt tomrom',
insert_image_align : 'Justering',
insert_image_align_default : '-- Ikke satt --',
insert_image_align_baseline : 'Bunnlinjen',
insert_image_align_top : 'Lengst opp',
insert_image_align_middle : 'Midten',
insert_image_align_bottom : 'Lengst ned',
insert_image_align_texttop : 'Tekstens topp',
insert_image_align_absmiddle : 'Absolutt midten',
insert_image_align_absbottom : 'Absolutt lengst ned',
insert_image_align_left : 'Venstre',
insert_image_align_right : 'Høyre',
insert_image_delta_width : 30,
insert_image_delta_height : 10,
theme_font_size : '-- Fontstørrelse --',
theme_fontdefault : '-- Fontfamilie --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraf',
theme_div : 'Div',
theme_address : 'Adresse',
theme_pre : 'Preformatert',
theme_h1 : 'Overskrift 1',
theme_h2 : 'Overskrift 2',
theme_h3 : 'Overskrift 3',
theme_h4 : 'Overskrift 4',
theme_h5 : 'Overskrift 5',
theme_h6 : 'Overskrift 6',
theme_blockquote : 'Blokksitat',
theme_code : 'Kode',
theme_samp : 'Eksempelkode',
theme_dt : 'Definisjon',
theme_dd : 'Definisjons beskrivelse',
theme_colorpicker_title : 'Velg en farge',
theme_colorpicker_apply : 'Bruk',
theme_forecolor_desc : 'Velg forgrunnsfarge',
theme_backcolor_desc : 'Velg bakgrunnsfarge',
theme_charmap_title : 'Velg spesialtegn',
theme_charmap_desc : 'Sett inn spesialtegn',
theme_visualaid_desc : 'Slå av/på usynlige elementer',
insert_anchor_title : 'Opprette/endre anker',
insert_anchor_name : 'Ankernavn',
theme_anchor_desc : 'Opprette/endre anker',
theme_insert_link_titlefield : 'Tittel',
theme_clipboard_msg : 'Kopier/Klipp ut/Lim inn er ikke tilgjengelig i Mozilla/Firefox.\nVil du ha mere informasjon om dette?',
theme_path : 'Sti',
cut_desc : 'Klipp ut',
copy_desc : 'Kopier',
paste_desc : 'Lim inn',
link_list : 'Lenkeliste',
image_list : 'Bildeliste',
browse : 'Bla gjennom',
image_props_desc : 'Bildeegenskaper',
newdocument_desc : 'Nytt dokument',
class_name : 'Stil',
newdocument : 'Er du sikker på at du vil tømme hele redigeringsområdet?',
about_title : 'Om TinyMCE',
about : 'Om',
license : 'Lisens',
plugins : 'Programtillegg',
plugin : 'Programtillegg',
author : 'Utviklere',
version : 'Versjon',
loaded_plugins : 'Lastede programtillegg',
help : 'Hjelp',
not_set : '-- Ikke satt --',
close : 'Stopp',
invalid_data : 'Feil: Ugyldige verdier er skrevet inn, disse er markert med rødt.',
toolbar_focus : 'Hopp til verktøylinje - Alt+Q, hopp til tekstbehandler - Alt-Z, Hopp til elementsti - Alt-X',
more_colors : 'Flere farger',
color_picker_tab : 'Samler',
color_picker : 'Fargesamler',
web_colors_tab : 'Nettleser-sikre',
web_colors : 'Nettleser-sikre farger',
named_colors_tab : 'Navngitte',
named_colors : 'Navngitte farger',
color : 'Farge:',
color_name : 'Navn:'
});
