tinyMCE.addI18n('nb.advanced',{
style_select:"Stiler",
font_size:"Skriftstørrelse",
fontdefault:"Skriftfamilie",
block:"Format",
paragraph:"Paragraf",
div:"Div",
address:"Adresse",
pre:"Forhåndsdefinert",
h1:"Overskrift 1",
h2:"Overskrift 2",
h3:"Overskrift 3",
h4:"Overskrift 4",
h5:"Overskrift 5",
h6:"Overskrift 6",
blockquote:"Sitat",
code:"Kode",
samp:"Kodeeksempel",
dt:"Definisjonsterm",
dd:"Definisjonsbeskrivelse",
span:"Span",
bold_desc:"Fet (Ctrl+B)",
italic_desc:"Kursiv (Ctrl+I)",
underline_desc:"Understreket (Ctrl+U)",
striketrough_desc:"Gjennomstreket",
justifyleft_desc:"Venstrejuster",
justifycenter_desc:"Midtstill",
justifyright_desc:"Høyrejuster",
justifyfull_desc:"Fyll ut linjen",
bullist_desc:"Usortert liste",
numlist_desc:"Sortert liste",
outdent_desc:"Reduser innrykk",
indent_desc:"Innrykk",
undo_desc:"Angre (Ctrl+Z)",
redo_desc:"Gjenta (Ctrl+Y)",
link_desc:"Sett inn/Endre lenke",
unlink_desc:"Fjern lenke",
image_desc:"Sett inn/Endre bilde",
cleanup_desc:"Rens grisete kode",
code_desc:"Rediger HTML-kode",
sub_desc:"Senket skrift",
sup_desc:"Hevet skrift",
hr_desc:"Sett inn horisontal linje",
removeformat_desc:"Fjern formatering",
custom1_desc:"Din beskrivelse her",
forecolor_desc:"Velg tekstfarge",
backcolor_desc:"Velg bakgrunnsfarge",
charmap_desc:"Sett inn spesialtegn",
visualaid_desc:"Slå av/på veiledere og usynlige elementer",
anchor_desc:"Sett inn/Endre anker",
cut_desc:"Klipp ut",
copy_desc:"Kopier",
paste_desc:"Lim inn",
image_props_desc:"Bildeegenskaper",
newdocument_desc:"Nytt dokument",
help_desc:"Hjelp",
blockquote_desc:"Sitat",
clipboard_msg:"Klipp og lim er ikke tilgjengelig i Mozilla og Firefox.\r\nØnsker du mer informasjon om dette problemet?",
path:"Sti",
newdocument:"Er du sikker på at du vil fjerne alt innhold?",
toolbar_focus:"Hopp til verktøyknapper - Alt+Q, Hopp til tekstfelt - Alt-Z, Hopp til elementsti - Alt-X",
more_colors:"Flere farger",
shortcuts_desc:'Tilgjengelighetshjelp',
help_shortcut:'. Klikk ALT+F10 for verktøylinje. Klikk ALT+0 for hjelp.',
rich_text_area:"Felt for rik tekst",
toolbar:"Verktøylinje"
});
