tinyMCE.addI18n('nb.advanced_dlg',{
about_title:"Om TinyMCE",
about_general:"Om",
about_help:"Hjelp",
about_license:"Lisens",
about_plugins:"Programtillegg",
about_plugin:"Programtillegg",
about_author:"Opphav",
about_version:"Versjon",
about_loaded:"Lastede programtillegg",
anchor_title:"Sett inn/Endre anker",
anchor_name:"Ankernavn",
anchor_invalid:"Du må angi et gyldig ankernavn."
code_title:"Kildekodebehandler",
code_wordwrap:"Tekstbryting",
colorpicker_title:"Velg en farge",
colorpicker_picker_tab:"Velg farge",
colorpicker_picker_title:"Fargevelger",
colorpicker_palette_tab:"Palett",
colorpicker_palette_title:"Palettfarger",
colorpicker_named_tab:"Navngitt",
colorpicker_template_tab:"Mal",
colorpicker_named_title:"Navngitte farger",
colorpicker_template_title:"Malfarger",
colorpicker_color:"Farge:",
colorpicker_name:"Navn:",
charmap_title:"Velg spesialtegn",
image_title:"Sett inn/Endre bilde",
image_src:"Bildeadresse",
image_alt:"Bildebeskrivelse",
image_list:"Bildeliste",
image_border:"Kantlinje",
image_dimensions:"Dimensjoner",
image_vspace:"Vertikal avstand",
image_hspace:"Horisontal avstand",
image_align:"Plassering",
image_align_baseline:"Nederst",
image_align_top:"Øverst",
image_align_middle:"Midtstilt",
image_align_bottom:"Bunn",
image_align_texttop:"Teksttopp",
image_align_textbottom:"Tekstbunn",
image_align_left:"Venstre",
image_align_right:"Høyre",
link_title:"Sett inn/Endre lenke",
link_url:"Lenkeadresse",
link_target:"Målside",
link_target_same:"Åpne i samme vindu",
link_target_blank:"åpne i nytt vindu",
link_titlefield:"Tittel",
link_is_email:"Nettadressen du skrev inn ser ut til å være en e-postadresse. ønsker du å legge til det påkrevde mailto:-prefikset?",
link_is_external:"Nettadressen du skrev inn ser ut til å være en ekstern nettadresse. ønsker du å legge til det påkrevde http://-prefikset?",
link_list:"Lenkeliste",
accessibility_help:"Tilgjengelighetshjelp",
accessibility_usage_title:"Generell bruk"
});
