tinyMCE.addI18n('nb.media_dlg''
{
list:"Liste"'
file:"Fil/URL"'
advanced:"Avansert"'
general:"Generelt"'
title:"Sett inn/Endre inkludert objekt"'
"align_top_left":"Topp venstre"'
"align_center":"Midtstill"'
"align_left":"Venstre"'
"align_bottom":"Bunn"'
"align_right":"Høyre"'
"align_top":"Topp"'
"qt_stream_warn":"Streamede rtsp-ressurser bør legges til QT Src-felt i avansert-fanen.\\nDu bør også legge til en ikke-streamet versjon i Src-felt"'
qtsrc:"QT Src"'
progress:"Framdrift"'
sound:"Lyd"'
swstretchvalign:"Strekk V-justering"'
swstretchhalign:"Strekk H-justering"'
swstretchstyle:"Strekkstil"'
scriptcallbacks:"Skript-referanser"'
"align_top_right":"Topp høyre"'
uimode:"UI-modus"'
rate:"Rate"'
playcount:"Teller"'
defaultframe:"Standardramme"'
currentposition:"Aktiv posisjon"'
currentmarker:"Aktiv markør"'
captioningid:"Fang opp id"'
baseurl:"Utgangsadresse (URL)"'
balance:"Balanse"'
windowlessvideo:"Video uten vindu"'
stretchtofit:"Strekk for å passe inn"'
mute:"Demp"'
invokeurls:"Aktiviser URL-er"'
fullscreen:"Fullskjerm"'
enabled:"Kjørbar"'
autostart:"Autostart"'
volume:"Volum"'
target:"Mål"'
qtsrcchokespeed:"Choke-hastighet"'
href:"Href"'
endtime:"Stopptid"'
starttime:"Starttid"'
enablejavascript:"Tillat Javaskript"'
correction:"Ingen korreksjon"'
targetcache:"Mål-mellomlagring"'
playeveryframe:"Spill hver ramme"'
kioskmode:"Kiosk-modus"'
controller:"Kontroller"'
menu:"Vis meny"'
loop:"Løkke"'
play:"Autostart"'
hspace:"Horisontal avstand"'
vspace:"Vertikal avstand"'
"class_name":"Klasse"'
name:"Navn"'
id:"Id"'
type:"Type"'
size:"Størrelse"'
preview:"Forhåndsvisning"'
"constrain_proportions":"Behold størrelsesforhold"'
controls:"Kontroller"'
numloop:"Antall gjennomløp"'
console:"Konsoll"'
cache:"Mellomlager"'
autohref:"AutoHREF"'
liveconnect:"SWLiveConnect"'
flashvars:"Flash-variabler"'
base:"Base"'
bgcolor:"Bakgrunn"'
wmode:"W-modus"'
salign:"S-justering"'
align:"Justering"'
scale:"Skalering"'
quality:"Kvalitet"'
shuffle:"Miks"'
prefetch:"Forhåndsregistrer"'
nojava:"Ingen Java"'
maintainaspect:"Behold størrelsesforhold"'
imagestatus:"Bildestatus"'
center:"Midtstill"'
autogotourl:"Auto-gå-til-URL"'
"shockwave_options":"Shockwave-innstillinger"'
"rmp_options":"Real mediaplayer-innstillinger"'
"wmp_options":"Windows mediaplayer-innstillinger"'
"qt_options":"Quicktime-innstillinger"'
"flash_options":"Flash-egenskaper"'
hidden:"Skjult"'
"align_bottom_left":"Bunn venstre"'
"align_bottom_right":"Bunn høyre"'
"flv_options":"Flash video-valg"'
"flv_scalemode":"Skalering"'
"flv_buffer":"Buffer"'
"flv_startimage":"Startbilde"'
"flv_starttime":"Starttid"'
"flv_defaultvolume":"Standardvolum"'
"flv_hiddengui":"Skjult GUI"'
"flv_autostart":"Auto-start"'
"flv_loop":"Løkke"'
"flv_showscalemodes":"Vis skalering"'
"flv_smoothvideo":"Jevn video"'
"flv_jscallback":"JS-tilbakekall"'
"html5_video_options":"HTML5-videovalg"'
altsource1:"Alternativ kilde 1"'
altsource2:"Alternativ kilde 2"'
preload:"Forhåndsvis"'
poster:"Poster"'
source:"Kilde"});
