tinyMCE.addI18n('nb.xhtmlxtras_dlg',{
attribute_label_title:"Tittel",
attribute_label_id:"ID",
attribute_label_class:"Klasse",
attribute_label_style:"Stil",
attribute_label_cite:"Sitat",
attribute_label_datetime:"Dato/tid",
attribute_label_langdir:"Tekst-retning",
attribute_option_ltr:"Venstre mot høyre",
attribute_option_rtl:"Høyre mot venstre",
attribute_label_langcode:"Språk",
attribute_label_tabindex:"Tab-index",
attribute_label_accesskey:"Hurtigstast",
attribute_events_tab:"Hendelser",
attribute_attrib_tab:"Egenskaper",
general_tab:"Vanlige",
attrib_tab:"Egenskaper",
events_tab:"Hendelser",
fieldset_general_tab:"Vanlige instillinger",
fieldset_attrib_tab:"Element-egenskaper",
fieldset_events_tab:"Element-hendelser",
title_ins_element:"Innsettings-element",
title_del_element:"Slettings-element",
title_acronym_element:"Kronym-element",
title_abbr_element:"Forkortelses-element",
title_cite_element:"Sitat-element",
remove:"Fjern",
insert_date:"Sett inn dagens dato/tid",
option_ltr:"venstre mot høyre",
option_rtl:"Høyre mot venstre",
attribs_title:"Sett inn / endre egenskaper"
});
