tinyMCE.addI18n('nb.advanced',{
style_select:"Stiler",
font_size:"Font størrelse",
fontdefault:"Font familie",
block:"Format",
paragraph:"Paragraf",
div:"Div",
address:"Adresse",
pre:"Preformatert",
h1:"Overskrift 1",
h2:"Overskrift 2",
h3:"Overskrift 3",
h4:"Overskrift 4",
h5:"Overskrift 5",
h6:"Overskrift 6",
blockquote:"Sitat",
code:"Kode",
samp:"Kodeprøve",
dt:"Definisjons term",
dd:"Definisjonsbeskrivelse",
bold_desc:"Fet stil (Ctrl+B)",
italic_desc:"Kursiv (Ctrl+I)",
underline_desc:"Understreket (Ctrl+U)",
striketrough_desc:"Gjennomstreket",
justifyleft_desc:"Venstrejuster",
justifycenter_desc:"Midtstill",
justifyright_desc:"Høyrejuster",
justifyfull_desc:"Fyll hele linjen",
bullist_desc:"Punktliste",
numlist_desc:"Ordnet punktliste",
outdent_desc:"Utdenter",
indent_desc:"Indenter",
undo_desc:"Angre (Ctrl+Z)",
redo_desc:"Gjenta (Ctrl+Y)",
link_desc:"Sett inn/endre lenke",
unlink_desc:"Fjern lenke",
image_desc:"Sett inn/endre bilde",
cleanup_desc:"Rens opp kode",
code_desc:"Editer HTML-kode",
sub_desc:"Senket skrift",
sup_desc:"Hevet skrift",
hr_desc:"Sett inn horisontal strek",
removeformat_desc:"Fjern formatering",
custom1_desc:"Din beskrivelse her",
forecolor_desc:"Velg tekstfarge",
backcolor_desc:"Velg bakgrunnsfarge",
charmap_desc:"Sett inn spesialtegn",
visualaid_desc:"Aktiver/deaktiver usynlige element og hjelpelinjer",
anchor_desc:"Sett inn/endre anker",
cut_desc:"Klipp ut",
copy_desc:"Kopier",
paste_desc:"Lim inn",
image_props_desc:"Bildeegenskaper",
newdocument_desc:"Nytt dokument",
help_desc:"Hjelp",
blockquote_desc:"Sitat",
clipboard_msg:"Klipp og lim er ikke tilgjengelig i Mozilla og Firefox.\r\n Vil du ha mer hjelp om klipp og lim?",
path:"Sti",
newdocument:"Er du sikker på at du vil fjerne alt innhold i dette dokumentet?",
toolbar_focus:"Hopp til verktøy-knapper - Alt+Q, Hopp til editor - Alt-Z, Hopp til element-sti - Alt-X",
more_colors:"Mer farger"
});
tinyMCE.addI18n('nb.advanced_dlg',{
charmap_title:"Velg spesialtegn"
});

