tinyMCE.addI18n('nb.advanced_dlg',{
about_title:"Om TinyMCE",
about_general:"Om",
about_help:"Hjelp",
about_license:"Lisens",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Forfatter",
about_version:"versjon",
about_loaded:"Lastede plugins",
anchor_title:"Sett inn/endre anker",
anchor_name:"Anker-navn",
code_title:"HTML-kilde-editor",
code_wordwrap:"Bryt lange linjer",
colorpicker_title:"Velg en farge",
colorpicker_picker_tab:"Velger",
colorpicker_picker_title:"Farge-velger",
colorpicker_palette_tab:"Palett",
colorpicker_palette_title:"Palett-farger",
colorpicker_named_tab:"Navngitt",
colorpicker_template_tab:"Templat",
colorpicker_named_title:"Navngitte farger",
colorpicker_template_title:"Templat-farger",
colorpicker_color:"Farge:",
colorpicker_name:"Navn:",
charmap_title:"Velg spesialtegn",
image_title:"Sett inn/endre bilde",
image_src:"Bilde-URL",
image_alt:"Bilde-beskrivelse",
image_list:"Bilde liste",
image_border:"Kant",
image_dimensions:"Dimensjoner",
image_vspace:"Mellomrom vertikalt",
image_hspace:"MEllomrom horisontalt",
image_align:"Bildeplassering",
image_align_baseline:"Baselinjen",
image_align_top:"Øverst",
image_align_middle:"Midt på",
image_align_bottom:"Nederst",
image_align_texttop:"Tekst øverst",
image_align_textbottom:"Tekst nederst",
image_align_left:"Venstre",
image_align_right:"Høyre",
link_title:"Sett inn/endre lenke",
link_url:"Lenke-URL",
link_target:"Mål",
link_target_same:"Åpne lenke i samme nettleser-vindu",
link_target_blank:"Åpne lenke i nytt nettleser-vindu",
link_titlefield:"Tittel",
link_is_email:"URLen du skrev inn ser ut til å være en epost-adresse, vil du legge til det nødvendige mailto:-prefikset?",
link_is_external:"URLen du skrev inn ser ut til å være en ekstern lenke, vil du legge til det nødvendige http://-prefikset?",
link_list:"Lenke-liste"
});
