tinyMCE.addI18n('nb.advanced_dlg',{
"link_list":"Lenkeliste",
"link_is_external":"Nettadressen du skrev inn ser ut til å være en ekstern nettadresse. ønsker du å legge til det påkrevde http://-prefikset?",
"link_is_email":"Nettadressen du skrev inn ser ut til å være en e-postadresse. ønsker du å legge til det påkrevde mailto:-prefikset?",
"link_titlefield":"Tittel",
"link_target_blank":"åpne i nytt vindu",
"link_target_same":"åpne i dette vinduet",
"link_target":"Målside",
"link_url":"Lenkens URL",
"link_title":"Sett inn/Endre lenke",
"image_align_right":"Høyre",
"image_align_left":"Venstre",
"image_align_textbottom":"Tekstbunn",
"image_align_texttop":"Teksttopp",
"image_align_bottom":"Bunn",
"image_align_middle":"Midtstilt",
"image_align_top":"Topp",
"image_align_baseline":"Bunnlinje",
"image_align":"Justering",
"image_hspace":"Horisontal avstand",
"image_vspace":"Vertikal avstand",
"image_dimensions":"Dimensjoner",
"image_alt":"Bildebeskrivelse",
"image_list":"Bildeliste",
"image_border":"Ramme",
"image_src":"Bildets URL",
"image_title":"Sett inn/Endre bilde",
"charmap_title":"Velg spesialtegn",
"colorpicker_name":"Navn:",
"colorpicker_color":"Farge:",
"colorpicker_named_title":"Fargenavn",
"colorpicker_named_tab":"Navnevalg",
"colorpicker_palette_title":"Palettfarger",
"colorpicker_palette_tab":"Palett",
"colorpicker_picker_title":"Fargevalg",
"colorpicker_picker_tab":"Velg farge",
"colorpicker_title":"Velg en farge",
"code_wordwrap":"Tekstbryting",
"code_title":"HTML-editor",
"anchor_name":"Ankernavn",
"anchor_title":"Sett inn/Endre anker",
"about_loaded":"Lastede programtillegg",
"about_version":"Versjon",
"about_author":"Utvikler",
"about_plugin":"Programtillegg",
"about_plugins":"Programtillegg",
"about_license":"Lisens",
"about_help":"Hjelp",
"about_general":"Om",
"about_title":"Om TinyMCE",
"anchor_invalid":"Du må angi et gyldig ankernavn."
});
