// NB lang variables

// Ferdig oversatt, 25. mai 2007

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Sitering',
abbr_desc : 'Forkortelse',
acronym_desc : 'Initaler',
del_desc : 'Sletting',
ins_desc : 'Innsetting',
attribute_label_title : 'Tittel',
attribute_label_id : 'ID',
attribute_label_class : 'Klasse',
attribute_label_style : 'Stil',
attribute_label_cite : 'Sted',
attribute_label_datetime : 'Dato/Tid',
attribute_label_langdir : 'Tekstretning',
attribute_option_ltr : 'Venstre til høyre',
attribute_option_rtl : 'Høyre til venstre',
attribute_label_langcode : 'Språk',
attribute_label_tabindex : 'Tabulatorindeks',
attribute_label_accesskey : 'Adgangsnøkkel',
attribute_label_cite : 'Sted',
attribute_events_tab : 'Hendelser',
attribute_attrib_tab : 'Egenskaper',
general_tab : 'Generelt',
attrib_tab : 'Egenskaper',
events_tab : 'Hendelser',
fieldset_general_tab : 'Generelle innstillinger',
fieldset_attrib_tab : 'Elementegenskaper',
fieldset_events_tab : 'Elementhendelser',
title_ins_element : 'Innsettelseselement',
title_del_element : 'Slettingselement',
title_acronym_element : 'Forkortelseselement',
title_abbr_element : 'Initialelement',
title_cite_element : 'Siteringselement',
remove : 'Fjern',
not_set : '--ikke satt--',
insert_date : 'Sett inn nåværende dato/tid',
option_ltr : 'Venstre til høyre',
option_rtl : 'Høyre til venstre',
attribs_desc : 'Sett inn/Rediger egenskaper',
attribs_title : 'Sett inn/Rediger egenskaper'
});
