// nb = Norwegian (bokmål) lang variables by Lars Bjarte Myren
// Bygger på tidligere arbeid av Knut B. Jacobsen og Jens-Christian Skibakk

// Ferdig oversatt, 25. mai 2007

tinyMCE.addToLang('',{
theme_style_select : '--Stiler--',
theme_code_desc : 'Redigere HTMLkoden',
theme_code_title : 'HTMLredigering',
theme_code_wordwrap : 'Linjebryting',
theme_sub_desc : 'Nedsenket skrift',
theme_sup_desc : 'Opphøyd skrift',
theme_hr_desc : 'Sett inn horisontal linje',
theme_removeformat_desc : 'Fjern formatering',
theme_custom1_desc : 'Din spesialfunksjons beskrivelse her',
insert_image_border : 'Ramme',
insert_image_dimensions : 'Dimensjoner',
insert_image_vspace : 'Vertikalt luft',
insert_image_hspace : 'Horisontalt luft',
insert_image_align : 'Justering',
insert_image_align_default : '-- Ikke satt --',
insert_image_align_baseline : 'Bunnlinjen',
insert_image_align_top : 'Lengst opp',
insert_image_align_middle : 'Midten',
insert_image_align_bottom : 'Bunn',
insert_image_align_texttop : 'Teksttopp',
insert_image_align_absmiddle : 'Absolutt midt',
insert_image_align_absbottom : 'Absolutt bunn',
insert_image_align_left : 'Venstre',
insert_image_align_right : 'Høyre',
theme_font_size : '-- Skriftstørrelse --',
theme_fontdefault : '-- Skriftfamilie --',
theme_block : '-- Format --',
theme_paragraph : 'Avsnitt',
theme_div : 'Div',
theme_address : 'Adresse',
theme_pre : 'Pre-formatert',
theme_h1 : 'Overskrift 1',
theme_h2 : 'Overskrift 2',
theme_h3 : 'Overskrift 3',
theme_h4 : 'Overskrift 4',
theme_h5 : 'Overskrift 5',
theme_h6 : 'Overskrift 6',
theme_blockquote : 'Sitatinnrykk',
theme_code : 'Kode',
theme_samp : 'Kodeeksempel',
theme_dt : 'Definisjonsuttrykk',
theme_dd : 'Definisjonsbeskrivelse',
theme_colorpicker_title : 'Velg en farge',
theme_colorpicker_apply : 'Bruk',
theme_forecolor_desc : 'Velg forgrunnsfarge',
theme_backcolor_desc : 'Velg bakgrunnsfarge',
theme_charmap_title : 'Velg spesialtegn',
theme_charmap_desc : 'Sett inn spesialtegn',
theme_visualaid_desc : 'Slå av/på usynlige elementer',
insert_anchor_title : 'Opprette/endre anker',
insert_anchor_name : 'Ankernavn',
theme_anchor_desc : 'Opprette/endre anker',
theme_insert_link_titlefield : 'Tittel',
theme_clipboard_msg : 'Kopier/Klipp ut/Lim inn er ikke tilgjengelig i Mozilla/Firefox.\nVil du ha mere informasjon om dette?',
theme_path : 'Søkesti',
cut_desc : 'Klipp ut',
copy_desc : 'Kopier',
paste_desc : 'Lim inn',
link_list : 'Lenkeliste',
image_list : 'Bildeliste',
browse : 'Bla gjennom',
image_props_desc : 'Bildeegenskaper',
newdocument_desc : 'Nytt dokument',
class_name : 'Stil',
newdocument : 'Er du sikker på at du vil tømme hele redigeringsområdet?',
about_title : 'Om TinyMCE',
about : 'Om',
license : 'Lisens',
plugins : 'Programtillegg',
plugin : 'Programtillegg',
author : 'Utviklere',
version : 'Versjon',
loaded_plugins : 'Lastet programtillegg',
help : 'Hjelp',
not_set : '-- Ikke satt --',
close : 'Lukk',
toolbar_focus : 'Hopp til verktøylinje - Alt+Q, hopp til teksbehandler - Alt+Z , hopp til elementsti - Alt+X',
invalid_data : 'Feil: Ugyldige, verdier merket med rødt, er angitt',
more_colors : 'Flere farger',
color_picker_tab : 'Velger',
color_picker : 'Fargevelger',
web_colors_tab : 'Nettsikker',
web_colors : 'Nettsikre farger',
named_colors_tab : 'Navngitt',
named_colors : 'Navngitte farger',
color : 'Farge:',
color_name : 'Navn:',
//JCE Sepcific
name : 'Navn',
ok : 'Ok',
unique : 'Opprett unik fil',
overwrite : 'Overskriv eksisterende fil',
folder : 'Mappe',
file : 'Fil',
upload : 'Last opp',
new_folder : 'Ny mappe',
rename_file : 'Endre filnavn',
rename_folder : 'Endre mappenavn',
delete_file_alert : 'Slett fil(er)?',
delete_folder_alert : 'Slett mappe?',
rename_alert : 'Ved å endre navn på file og mapper vil eksisterende lenker bli brutt. Vil du fortsette?',
files_select : 'Valgte filer',
template_colors : 'Fargepalett',
no_template_colors : 'Ingen farger er definert',
loading : 'Henter...',
uploading : 'Laster opp...',
loader: 'Henter data...',
alert : 'Advarsel!',
confirm : 'Bekreft',
yes : 'Ja',
no : 'Nei'
});