tinyMCE.addI18n('nb.imgmanager_ext_dlg',{
missing_alt: "Er du sikker på at du vil fortsette uten å inkludere en alternativ tekst for bildet? Uten dette vil kanskje ikke bildet være tilgjengelig for brukere med handikapp, eller for dem som bruker tekstlesere, eller som surfer nettet med bilder avslått.",
delta_width: 0,
delta_height: 0,
'0':'Original',
'-90': '90&deg; CW',
'90': '90&deg; CCW',
'180': '180&deg;',
'vertical': 'Vend vertikalt',
'horizontal': 'Vend horisontalt',
'view_images': 'Minityrbildevisning',
'view_list': 'Listevisning',
'use_thumbnail': 'Bruk assosiert miniatyrbilde for sprettopplenke?',
'resize': 'Endre størrelse',
'rotate': 'Roter',
'proportional': 'Proporsjonalt',
'cropped': 'Kuttet',
'mode': 'Modus',
'quality': 'Kvalitet',
'size': 'Størrelse',
'thumbnail': 'Miniatyrbilde',
'transform': 'Transform',
'width': 'Bredde',
'height': 'Høyde',
'create_thumbnail': 'Opprett miniatyrbilde',
'delete_thumbnail': 'Slett miniatyrbilde?',
'message_images': 'Click on an image to view its properties, double-click to insert it. CTRL+Click selects multiple images.',
'message_list': 'Click on an image name to insert, click to the right of the name to view its properties. CTRL+Click selects multiple images.',
'no_src': 'Please select an image or enter an image URL.',
'no_popup_src' : 'Please enter a url for the popup image',
'upload_resize_tip' : 'Resize::Resize the uploaded images to fit within the specified width and height whilst maintaining the aspect ratio of the original image.',
'upload_thumbnail_tip' : 'Thumbnail::Create a thumbnail of the uploaded image using the specified dimensions, dynamically cropping the thumbnail image to fit within these dimensions if necessary.',
'upload_thumbnail_crop':'Beskjær til å passe',
'upload_thumbnail_crop_tip':'Crop To Fit::Crop the thumbnail to fit within the specified dimensions',
'greyscale' : 'Gråskala',
'sepia'	: ' Sepia',
'invert' : 'Negativ',
'lighten' : 'Gjør lysere',
'darken' : 'Gjør mørkere',
'saturate' : 'Boost',
'desaturate' : 'Fade',
'threshold' : 'Svarthvit',
'halftone' : 'Tegneserie',
'create_thumbnail_failed':'Kunne ikke opprette minityrbilde'
});
