tinyMCE.addI18n('nb.table_dlg',{
general_tab:"Generell",
advanced_tab:"Avansert",
general_props:"Generelle egenskaper",
advanced_props:"Avanserte egenskaper",
rowtype:"Rad i tabell-del",
title:"Sett inn/endre tabell",
width:"Bredde",
height:"Høyde",
cols:"Kolonner",
rows:"Rader",
cellspacing:"Celle-mellomrom",
cellpadding:"Celle-avstand",
border:"Kantlinje",
align:"Oppstilling",
align_default:"Standard",
align_left:"Venstre",
align_right:"Høyre",
align_middle:"Senter",
row_title:"Tabellrad egenskaper",
cell_title:"Tabellcelle egenskaper",
cell_type:"Celletype",
valign:"Vertikaloppstilling",
align_top:"Øverst",
align_bottom:"Nederst",
bordercolor:"Kantfarge",
bgcolor:"Bakgrunnsfarge",
merge_cells_title:"Slå sammen tabellceller",
id:"Id",
style:"Stil",
langdir:"Språkretning",
langcode:"Språk kode",
mime:"MIME-type for mål",
ltr:"Venstre mot høyre",
rtl:"Høyre mot venstre",
bgimage:"Bakgrunnsbilde",
summary:"Sammendrag",
td:"Data",
th:"Tittel",
cell_cell:"Oppdater valgt celle",
cell_row:"Oppdater alle celler i rad",
cell_all:"Oppdater alle celler i tabell",
row_row:"Oppdater valgt rad",
row_odd:"Oppdater odde rader i tabell",
row_even:"Oppdater jevne rader i tabell",
row_all:"Oppdater alle rader i tabell",
thead:"Tabell-hode",
tbody:"Tabell-kropp",
tfoot:"Tabellfot",
scope:"Omfang",
rowgroup:"Radgruppe",
colgroup:"Kolonnegruppe",
col_limit:"Du har overgått maks antall kolonner {$cols}.",
row_limit:"Du har overgått maks antall rader {$rows}.",
cell_limit:"Du har overgått maks antall celler {$cells}.",
missing_scope:"Er du sikker på at du vil fortsette uten å definere et omfang for denne tabell-hode-cellen? Uten dette, vil det være vanskelilg for brukere med handikap å forstå innhold eller data i tabellen.",
caption:"Tabell-tekst",
frame:"Ramme",
frame_none:"ingen",
frame_groups:"grupper",
frame_rows:"rader",
frame_cols:"kolonner",
frame_all:"alle",
rules:"Regler",
rules_void:"tom",
rules_above:"over",
rules_below:"under",
rules_hsides:"hsider",
rules_lhs:"vhs",
rules_rhs:"hhs",
rules_vsides:"vsider",
rules_box:"boks",
rules_border:"kantline"
});
