tinyMCE.addI18n('en.dlg',{
// JCE specific
modified: 'Endret',
file: 'Fil',
folder: 'Mappe',
files: 'filer',
folders: 'mapper',
comments: 'Kommentarer',
size: 'Størrelse',
preview: 'Forhåndsvisning',
duration: 'Varighet',
dimensions: 'Dimensjoner',
contents: 'Innhold',
unwritable: 'Kan ikke skrives til',
bad_name: 'Feil i fil/mappe -navn',
message_tree: 'Lager tre-liste...',
message_load: 'Laster inn...',
message_properties: 'Henter instillinger...',
current_dir: 'Mappen du står i er: ',
help: 'Hjelp',
name: 'Navn',
uploading: 'Laster opp...',
upload: 'Last opp',
queue: 'Legg i køen',
upload_exits: 'Handling hvis fil finnes: ',
overwrite: 'Overskriv fil',
unique: 'Lag nytt navn',
cancel: 'Avbryt',
ok: 'OK',
browse: 'Bla',
'options': 'Valg',
'confirm': 'Bekreft',
yes: 'Ja',
no: 'Nei',
'alert': 'Alarm',
new_folder: 'Ny mappe',
rename: 'Gi nytt navn',
'delete': 'Slett',
delete_folder_alert: 'Slett mappe?',
delete_file_alert: 'Slett fil(er)?',
rename_folder: 'Gi mappe nytt navn',
rename_file: 'Gi fil nytt navn',
rename_alert: 'Endre navn på filer og mapper vil gjøre så eksisterende lenker ikke lengre fungerer.  Fortsette allikevel?',
file_select: 'Klikk på et filnavn for å legge til, klikk til høyre for filnavnet for å se filens attributter. CTRL+Click for å velge flere filer.',
notwritable: 'Ikke skrivbar',
notwritable_desc: 'Ikke skrivbar: mappe eller fil er ikke skrivbar, og kan derfor ikke gis nytt navn, flyttes eller slettes.',
bad_name: 'Feil i filnavn eller mappenavn. Unngå spesialtegn i navn på filer og mapper, også tegn som æ, ø og å',
bad_name_desc: 'Feil i filnavn eller mappenavn. Unngå spesialtegn i navn på filer og mapper, også tegn som æ, ø og å. kun tegnene a-zA-Z0-9_-. kan inngå i navnene',
select_value: 'Legg til verdi'
});
