// NB lang variables

// Ferdig oversatt, 25. mai 2007

tinyMCE.addToLang('style',{
title : 'Rediger CSS stil',
styleinfo_desc : 'Rediger CSS stil',
apply : 'Bruk',
text_tab : 'Tekst',
background_tab : 'Bakgrunn',
block_tab : 'Blokk',
box_tab : 'Boks',
border_tab : 'Ramme',
list_tab : 'Liste',
positioning_tab : 'Posisjon',
text_props : 'Tekst',
text_font : 'Skrifttype',
text_size : 'Skriftstørrelse',
text_weight : 'Teksttykkelse',
text_style : 'Stil',
text_variant : 'Variant',
text_lineheight : 'Linjeavstand',
text_case : 'Bokstavtype',
text_color : 'Farge',
text_decoration : 'Dekorering',
text_overline : 'overstreking',
text_underline : 'understreking',
text_striketrough : 'gjennomstreking',
text_blink : 'blinking',
text_none : 'ingen',
background_color : 'Bakgrunnsfarge',
background_image : 'Bakgrunnsbilde',
background_repeat : 'Gjentagelse',
background_attachment : 'Feste',
background_hpos : 'Horisontal posisjon',
background_vpos : 'Vertikal posisjon',
block_wordspacing : 'Ordmellomrom',
block_letterspacing : 'Bokstavmellomrom',
block_vertical_alignment : 'Vertikal justering',
block_text_align : 'Tekstjustering',
block_text_indent : 'Tekstinnrykk',
block_whitespace : 'Blanktegn',
block_display : 'Vis',
box_width : 'Bredde',
box_height : 'Høyde',
box_float : 'Flyt',
box_clear : 'Tøm',
padding : 'Luft',
same : 'Samme for alt',
top : 'Topp',
right : 'Høyre',
bottom : 'Bunn',
left : 'Venstre',
margin : 'Margin',
style : 'Stil',
width : 'Bredde',
height : 'Høyde',
color : 'Farge',
list_type : 'Type',
bullet_image : 'Punkttegn',
position : 'Posisjon',
positioning_type : 'Type',
visibility : 'Synlighet',
zindex : 'Z-indeks',
overflow : 'Overskudd',
placement : 'Plassering',
clip : 'Kutting'
});
