<?php
if( !defined( '_VALID_MOS' ) && !defined( '_JEXEC' ) ) die( 'Direct Access to '.basename(__FILE__).' is not allowed.' ); 
/**
*
* @version $Id$
* @package VirtueMart
* @subpackage languages
* @copyright Copyright (C) 2004-2008 soeren - All rights reserved.
* Translation is based on old language file for VM 1.0.
* New translation and cleanup for v1.1 by Odd-Eirik Eriksen (abc@abc-konsult.no) and Rune Rasmussen (syntaxerror.no).
* @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php
* VirtueMart is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
* See /administrator/components/com_virtuemart/COPYRIGHT.php for copyright notices and details.
*
* http://virtuemart.net
*/
global $VM_LANG;
$langvars = array (
	'CHARSET' => 'UTF-8',
	'PHPSHOP_MODULE_LIST_ORDER' => 'Rekkefølge',
	'PHPSHOP_PRODUCT_INVENTORY_LBL' => 'Produktbeholdning',
	'PHPSHOP_PRODUCT_INVENTORY_STOCK' => 'Nummer',
	'PHPSHOP_PRODUCT_INVENTORY_WEIGHT' => 'Vekt',
	'PHPSHOP_PRODUCT_LIST_PUBLISH' => 'Publiser',
	'PHPSHOP_PRODUCT_LIST_SEARCH_BY_DATE' => 'Produktsøk',
	'PHPSHOP_PRODUCT_LIST_SEARCH_BY_DATE_TYPE_PRODUCT' => 'Endret',
	'PHPSHOP_PRODUCT_LIST_SEARCH_BY_DATE_TYPE_PRICE' => 'Med endret pris',
	'PHPSHOP_PRODUCT_LIST_SEARCH_BY_DATE_TYPE_WITHOUTPRICE' => 'Uten pris',
	'PHPSHOP_PRODUCT_LIST_SEARCH_BY_DATE_AFTER' => 'Etter',
	'PHPSHOP_PRODUCT_LIST_SEARCH_BY_DATE_BEFORE' => 'Før',
	'PHPSHOP_PRODUCT_FORM_SHOW_FLYPAGE' => 'Se produktsiden i butikken',
	'PHPSHOP_PRODUCT_FORM_NEW_PRODUCT_LBL' => 'Nytt produkt',
	'PHPSHOP_PRODUCT_FORM_PRODUCT_INFO_LBL' => 'Produktinformasjon',
	'PHPSHOP_PRODUCT_FORM_PRODUCT_STATUS_LBL' => 'Produktstatus',
	'PHPSHOP_PRODUCT_FORM_PRODUCT_DIM_WEIGHT_LBL' => 'Produktets dimensjoner og vekt',
	'PHPSHOP_PRODUCT_FORM_PRODUCT_IMAGES_LBL' => 'Produktbilder',
	'PHPSHOP_PRODUCT_FORM_UPDATE_ITEM_LBL' => 'Oppdater artikkel',
	'PHPSHOP_PRODUCT_FORM_ITEM_INFO_LBL' => 'Artikkelinformasjon',
	'PHPSHOP_PRODUCT_FORM_ITEM_STATUS_LBL' => 'Artikkelstatus',
	'PHPSHOP_PRODUCT_FORM_ITEM_DIM_WEIGHT_LBL' => 'Artikkelens dimensjoner og vekt',
	'PHPSHOP_PRODUCT_FORM_ITEM_IMAGES_LBL' => 'Artikkelbilder',
	'PHPSHOP_PRODUCT_FORM_IMAGE_UPDATE_LBL' => 'Skriv inn stien til aktuelt bilde for å oppdatere det.',
	'PHPSHOP_PRODUCT_FORM_IMAGE_DELETE_LBL' => 'Slett bilde',
	'PHPSHOP_PRODUCT_FORM_PRODUCT_ITEMS_LBL' => 'Produktartikler',
	'PHPSHOP_PRODUCT_FORM_ITEM_ATTRIBUTES_LBL' => 'Produktvarianter',
	'PHPSHOP_PRODUCT_FORM_DELETE_PRODUCT_MSG' => 'Er du sikker på at du vil slette dette produktet\og artikler relatert til det?',
	'PHPSHOP_PRODUCT_FORM_DELETE_ITEM_MSG' => 'Er du sikker på at du vil slette denne artikkelen?',
	'PHPSHOP_PRODUCT_FORM_MANUFACTURER' => 'Produsent',
	'PHPSHOP_PRODUCT_FORM_SKU' => 'Varenummer',
	'PHPSHOP_PRODUCT_FORM_NAME' => 'Navn',
	'PHPSHOP_PRODUCT_FORM_CATEGORY' => 'Kategori',
	'PHPSHOP_PRODUCT_FORM_AVAILABLE_DATE' => 'Tilgjengelig dato',
	'PHPSHOP_PRODUCT_FORM_SPECIAL' => 'På tilbud',
	'PHPSHOP_PRODUCT_FORM_DISCOUNT_TYPE' => 'Rabattype',
	'PHPSHOP_PRODUCT_FORM_PUBLISH' => 'Publisere?',
	'PHPSHOP_PRODUCT_FORM_LENGTH' => 'Lengde',
	'PHPSHOP_PRODUCT_FORM_WIDTH' => 'Bredde',
	'PHPSHOP_PRODUCT_FORM_HEIGHT' => 'Høyde',
	'PHPSHOP_PRODUCT_FORM_DIMENSION_UOM' => 'Måleenhet',
	'PHPSHOP_PRODUCT_FORM_WEIGHT_UOM' => 'Måleenhet',
	'PHPSHOP_PRODUCT_FORM_FULL_IMAGE' => 'Stort bilde',
	'PHPSHOP_PRODUCT_FORM_WEIGHT_UOM_DEFAULT' => 'gram',
	'PHPSHOP_PRODUCT_FORM_DIMENSION_UOM_DEFAULT' => 'mm',
	'PHPSHOP_PRODUCT_FORM_PACKAGING' => 'Stk per pakke',
	'PHPSHOP_PRODUCT_FORM_PACKAGING_DESCRIPTION' => 'Her kan du fylle inn et nummer, antall per pakken.(maks 65535)',
	'PHPSHOP_PRODUCT_FORM_BOX' => 'Ant. i pakken',
	'PHPSHOP_PRODUCT_FORM_BOX_DESCRIPTION' => 'Her kan du skrive inn antall i pakken (maks 65535)',
	'PHPSHOP_PRODUCT_DISPLAY_ADD_PRODUCT_LBL' => 'Resultater lagt til',
	'PHPSHOP_PRODUCT_DISPLAY_UPDATE_PRODUCT_LBL' => 'Resultater oppdatert',
	'PHPSHOP_PRODUCT_DISPLAY_ADD_ITEM_LBL' => 'Artikkel lagt til resultat',
	'PHPSHOP_PRODUCT_DISPLAY_UPDATE_ITEM_LBL' => 'Artikkel oppdatert resultat',
	'PHPSHOP_CATEGORY_FORM_LBL' => 'Informasjon om kategorien',
	'PHPSHOP_CATEGORY_FORM_NAME' => 'Kategorinavn',
	'PHPSHOP_CATEGORY_FORM_PARENT' => 'Plassering',
	'PHPSHOP_CATEGORY_FORM_DESCRIPTION' => 'Kategoribeskrivelse',
	'PHPSHOP_CATEGORY_FORM_PUBLISH' => 'Publisere?',
	'PHPSHOP_CATEGORY_FORM_FLYPAGE' => 'Kategoribeskrivelse',
	'PHPSHOP_ATTRIBUTE_LIST_LBL' => 'Variantliste for',
	'PHPSHOP_ATTRIBUTE_LIST_NAME' => 'Variantnavn',
	'PHPSHOP_ATTRIBUTE_LIST_ORDER' => 'Rekkefølge',
	'PHPSHOP_ATTRIBUTE_FORM_LBL' => 'Variantskjema',
	'PHPSHOP_ATTRIBUTE_FORM_NEW_FOR_PRODUCT' => 'Ny variant for produkt',
	'PHPSHOP_ATTRIBUTE_FORM_UPDATE_FOR_PRODUCT' => 'Oppdater variant for produkt',
	'PHPSHOP_ATTRIBUTE_FORM_NEW_FOR_ITEM' => 'Ny variant for artikkel',
	'PHPSHOP_ATTRIBUTE_FORM_UPDATE_FOR_ITEM' => 'Oppdater variant for artikkel',
	'PHPSHOP_ATTRIBUTE_FORM_NAME' => 'Variantnavn',
	'PHPSHOP_ATTRIBUTE_FORM_ORDER' => 'Rekkefølge',
	'PHPSHOP_PRICE_LIST_FOR_LBL' => 'Pris for',
	'PHPSHOP_PRICE_LIST_GROUP_NAME' => 'Gruppenavn',
	'PHPSHOP_PRICE_LIST_PRICE' => 'Pris',
	'PHPSHOP_PRODUCT_LIST_CURRENCY' => 'Valuta',
	'PHPSHOP_PRICE_FORM_LBL' => 'Prisinformasjon',
	'PHPSHOP_PRICE_FORM_NEW_FOR_PRODUCT' => 'Ny pris for produkt',
	'PHPSHOP_PRICE_FORM_UPDATE_FOR_PRODUCT' => 'Oppdater pris for produkt',
	'PHPSHOP_PRICE_FORM_NEW_FOR_ITEM' => 'Ny pris for artikkel',
	'PHPSHOP_PRICE_FORM_UPDATE_FOR_ITEM' => 'Oppdater pris for artikkel',
	'PHPSHOP_PRICE_FORM_PRICE' => 'Pris',
	'PHPSHOP_PRICE_FORM_CURRENCY' => 'Valuta',
	'PHPSHOP_PRICE_FORM_GROUP' => 'Kundegruppe',
	'PHPSHOP_LEAVE_BLANK' => '(la dette feltet stå tomt om du <br />ikke har en individuell php-fil for det!)',
	'PHPSHOP_PRODUCT_FORM_ITEM_LBL' => 'Artikkel',
	'PHPSHOP_PRODUCT_DISCOUNT_STARTDATE' => 'Startdato for rabatt',
	'PHPSHOP_PRODUCT_DISCOUNT_STARTDATE_TIP' => 'Bestemmer datoen rabatten starter.',
	'PHPSHOP_PRODUCT_DISCOUNT_ENDDATE' => 'Sluttdato for rabatt',
	'PHPSHOP_PRODUCT_DISCOUNT_ENDDATE_TIP' => 'Bestemmer datoen rabatten slutter.',
	'PHPSHOP_FILEMANAGER_PUBLISHED' => 'Publisert?',
	'PHPSHOP_FILES_LIST' => 'Filkontroll:Bilde-/filliste for',
	'PHPSHOP_FILES_LIST_FILENAME' => 'Filnavn',
	'PHPSHOP_FILES_LIST_FILETITLE' => 'Filtittel',
	'PHPSHOP_FILES_LIST_FILETYPE' => 'Filtype',
	'PHPSHOP_FILES_LIST_FULL_IMG' => 'Stort bilde',
	'PHPSHOP_FILES_LIST_THUMBNAIL_IMG' => 'Lite bilde',
	'PHPSHOP_FILES_FORM' => 'Last opp en fil for',
	'PHPSHOP_FILES_FORM_CURRENT_FILE' => 'Gjeldende fil',
	'PHPSHOP_FILES_FORM_FILE' => 'Fil',
	'PHPSHOP_FILES_FORM_IMAGE' => 'Bilde',
	'PHPSHOP_FILES_FORM_UPLOAD_TO' => 'Last opp til',
	'PHPSHOP_FILES_FORM_UPLOAD_IMAGEPATH' => 'Standard sti til produktbilde',
	'PHPSHOP_FILES_FORM_UPLOAD_OWNPATH' => 'Spesifiser hvor filen er',
	'PHPSHOP_FILES_FORM_UPLOAD_DOWNLOADPATH' => 'Nedlastingssti (når du selger nedlastbare produkter!)',
	'PHPSHOP_FILES_FORM_AUTO_THUMBNAIL' => 'Autogenerere lite bilde?',
	'PHPSHOP_FILES_FORM_FILE_PUBLISHED' => 'Filen er publisert?',
	'PHPSHOP_FILES_FORM_FILE_TITLE' => 'Tittel for fil (som kunden ser)',
	'PHPSHOP_FILES_FORM_FILE_URL' => 'Fil URL (valgfri)',
	'PHPSHOP_PRODUCT_FORM_AVAILABILITY_TOOLTIP1' => 'Her kan du skrive inn produktets tilgjengelighet, leveringstid osv. (denne teksten vises på produktsiden).<br />f.eks.: 24t, 3-5 dager, Bestillingsvare.....',
	'PHPSHOP_PRODUCT_FORM_AVAILABILITY_TOOLTIP2' => 'ELLER velg et bilde som viser dette.<br />Bildene ligger her: <i>%s</i><br />',
	'PHPSHOP_PRODUCT_FORM_CUSTOM_ATTRIBUTE_LIST_EXAMPLES' => '<h4>Eksempler på egendefinerte attributter:</h4>
        <pre>Name;Extras;...</pre>',
	'PHPSHOP_IMAGE_ACTION' => 'Bildebehandling',
	'PHPSHOP_PARAMETERS_LBL' => 'Parametre',
	'PHPSHOP_PRODUCT_TYPE_LBL' => 'Produkttype',
	'PHPSHOP_PRODUCT_PRODUCT_TYPE_LIST_LBL' => 'Produkttype for',
	'PHPSHOP_PRODUCT_PRODUCT_TYPE_FORM_LBL' => 'Legg til produkttype for',
	'PHPSHOP_PRODUCT_PRODUCT_TYPE_FORM_PRODUCT_TYPE' => 'Produkttype',
	'PHPSHOP_PRODUCT_TYPE_FORM_NAME' => 'Produkttype, navn',
	'PHPSHOP_PRODUCT_TYPE_FORM_DESCRIPTION' => 'Produkttype, beskrivelse',
	'PHPSHOP_PRODUCT_TYPE_FORM_PARAMETERS' => 'Parameter',
	'PHPSHOP_PRODUCT_TYPE_FORM_LBL' => 'Produkttype, informasjon',
	'PHPSHOP_PRODUCT_TYPE_FORM_PUBLISH' => 'Publiser?',
	'PHPSHOP_PRODUCT_TYPE_FORM_BROWSEPAGE' => 'Produkttype, visningsside',
	'PHPSHOP_PRODUCT_TYPE_FORM_FLYPAGE' => 'Produkttype, detaljside (flypage)',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_LIST_LBL' => 'Parameter for produkttype',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_LBL' => 'Parameterinfo',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_NOT_FOUND' => 'Produkttype finnes ikke',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_NAME' => 'Parameternavn',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_NAME_DESCRIPTION' => 'Dette vil bli kolonnetittel. Navnet må være unikt, uten mellomrom<br />For eksempel: hoved_type',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_LABEL' => 'Parameter, etikett',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_TYPE_INTEGER' => 'Heltall',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_TYPE_TEXT' => 'Tekst',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_TYPE_SHORTTEXT' => 'Kort tekst',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_TYPE_FLOAT' => 'Flyt',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_TYPE_CHAR' => 'Bokstav',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_TYPE_DATETIME' => 'Dato og tid',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_TYPE_DATE' => 'Dato',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_TYPE_TIME' => 'Tid',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_TYPE_BREAK' => 'Break Line',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_TYPE_MULTIVALUE' => 'Flere verdier',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_VALUES' => 'Mulige verdier',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_MULTISELECT' => 'Vis mulige verdier som "Velg flere"?',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_VALUES_DESCRIPTION' => '<strong>Hvis mulige verdier er oppgitt, kan parametrene kun ha disse verdiene. Eksempel på mulige verdier:</strong><br/><span class="sectionname">Stål;Tre;Plast;...</span>',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_DEFAULT' => 'Standard verdi',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_DEFAULT_HELP_TEXT' => 'For forhåndsdefinert verdi bruk dette formatet:<ul><li>Date: YYYY-MM-DD</li><li>Time: HH:MM:SS</li><li>Date & Time: YYYY-MM-DD HH:MM:SS</li></ul>',
	'PHPSHOP_PRODUCT_TYPE_PARAMETER_FORM_UNIT' => 'Enhet',
	'PHPSHOP_PRODUCT_CLONE' => 'Dupliser produkt',
	'PHPSHOP_HIDE_OUT_OF_STOCK' => 'Skjul produkter som ikke er på lager',
	'PHPSHOP_FEATURED_PRODUCTS_LIST_LBL' => 'Kampanjeprodukter',
	'PHPSHOP_FEATURED' => 'Kampanje',
	'PHPSHOP_SHOW_FEATURED_AND_DISCOUNTED' => 'Kampanje- og rabatterte produkter',
	'PHPSHOP_SHOW_DISCOUNTED' => 'Rabatterte produkter',
	'PHPSHOP_FILTER' => 'Filter',
	'PHPSHOP_PRODUCT_FORM_DISCOUNTED_PRICE' => 'Rabattert pris',
	'PHPSHOP_PRODUCT_FORM_DISCOUNTED_PRICE_TIP' => 'Her kan du overstyre rabattinstillingene, fyll inn en spesiell rabatt for dette produktet.<br/>
		Nettbutikken vil automatisk generere en ny oppføring ut fra den rabatterte prisen.',
	'PHPSHOP_PRODUCT_LIST_QUANTITY_START' => 'Startantall',
	'PHPSHOP_PRODUCT_LIST_QUANTITY_END' => 'Sluttantall',
	'VM_PRODUCTS_MOVE_LBL' => 'Flytt produkter fra en kategori til en annen',
	'VM_PRODUCTS_MOVE_LIST' => 'Du har valgt å flytte følgende %s produkter',
	'VM_PRODUCTS_MOVE_TO_CATEGORY' => 'Flytt til følgende kategori',
	'VM_PRODUCT_LIST_REORDER_TIP' => 'Velg en produktkategori å endre produktrekkefølge i',
	'VM_REVIEW_FORM_LBL' => 'Legg til produktomtale',
	'PHPSHOP_REVIEW_EDIT' => 'Legg til/endre en produktomtale',
	'SEL_CATEGORY' => 'Velg en kategori',
	'VM_PRODUCT_FORM_MIN_ORDER' => 'Min. antall',
	'VM_PRODUCT_FORM_MAX_ORDER' => 'Maks. antall',
	'VM_DISPLAY_TABLE_HEADER' => 'Vis tabelloverskrift',
	'VM_DISPLAY_LINK_TO_CHILD' => 'Link til tilhørende produkt fra liste',
	'VM_DISPLAY_INCLUDE_PRODUCT_TYPE' => 'Inkluder produkttype med tilhørende produkt',
	'VM_DISPLAY_USE_LIST_BOX' => 'Bruk listeboks for underprodukter',
	'VM_DISPLAY_LIST_STYLE' => 'Listestil',
	'VM_DISPLAY_USE_PARENT_LABEL' => 'Bruk hovedproduktets innstillinger:',
	'VM_DISPLAY_LIST_TYPE' => 'List opp:',
	'VM_DISPLAY_QUANTITY_LABEL' => 'Antall:',
	'VM_DISPLAY_QUANTITY_DROPDOWN_LABEL' => 'Verdier for nedtrekksmeny',
	'VM_DISPLAY_CHILD_DESCRIPTION' => 'Vis beskrivelse for tilhørende produkt',
	'VM_DISPLAY_DESC_WIDTH' => 'Bredde for beskrivelse av tilhørende produkt',
	'VM_DISPLAY_ATTRIB_WIDTH' => 'Bredde for tilhørende produkts attributter',
	'VM_DISPLAY_CHILD_SUFFIX' => 'Endelse for underklasse',
	'VM_INCLUDED_PRODUCT_ID' => 'Inkluder produkt-ID\'er',
	'VM_EXTRA_PRODUCT_ID' => 'Ekstra ID\'er',
	'PHPSHOP_DISPLAY_RADIOBOX' => 'Bruk radiknapp',
	'PHPSHOP_PRODUCT_FORM_ITEM_DISPLAY_LBL' => 'Visning',
	'PHPSHOP_DISPLAY_USE_PARENT' => 'Overstyr tilhørende produkts verdier og bruk hovedproduktets verdier',
	'PHPSHOP_DISPLAY_NORMAL' => 'Forhåndsdefinert antall',
	'PHPSHOP_DISPLAY_HIDE' => 'Skjul forhåndsdefinert antall',
	'PHPSHOP_DISPLAY_DROPDOWN' => 'Bruk nedtrekksmeny',
	'PHPSHOP_DISPLAY_CHECKBOX' => 'Bruk avkrysningsboks',
	'PHPSHOP_DISPLAY_ONE' => 'En "Legg i handlekurv" knapp',
	'PHPSHOP_DISPLAY_MANY' => 'Egen "Legg i handlekurv" knapp for hvert tilhørende produkt',
	'PHPSHOP_DISPLAY_START' => 'Startverdi',
	'PHPSHOP_DISPLAY_END' => 'Sluttverdi',
	'PHPSHOP_DISPLAY_STEP' => 'Trinnverdi',
	'PRODUCT_WAITING_LIST_TAB' => 'Venteliste',
	'PRODUCT_WAITING_LIST_USERLIST' => 'Kunder som venter på melding om når dette produktet er på lager igjen',
	'PRODUCT_WAITING_LIST_NOTIFYUSERS' => 'Send melding til disse kundene nå (husk å oppdatere lagerbeholdningen først!)',
	'PRODUCT_WAITING_LIST_NOTIFIED' => 'melding sendt',
	'VM_PRODUCT_FORM_AVAILABILITY_SELECT_IMAGE' => 'Velg bilde',
	'VM_PRODUCT_RELATED_SEARCH' => 'Søk etter produkter eller kategorier her:',
	'VM_FILES_LIST_ROLE' => 'Rolle',
	'VM_FILES_LIST_UP' => 'Opp',
	'VM_FILES_LIST_GO_UP' => 'Gå opp',
	'VM_CATEGORY_FORM_PRODUCTS_PER_ROW' => 'Antall produkter per rad',
	'VM_CATEGORY_FORM_BROWSE_PAGE' => 'Kategorivisning',
	'VM_PRODUCT_CLONE_OPTIONS_TAB' => 'Alternativer for produktkloning',
	'VM_PRODUCT_CLONE_OPTIONS_LBL' => 'Klon også disse tilhørende produktene',
	'VM_PRODUCT_LIST_MEDIA' => 'Media',
	'VM_REVIEW_LIST_NAMEDATE' => 'Navn/Dato',
	'VM_PRODUCT_SELECT_ONE_OR_MORE' => 'Velg ett eller flere produkter',
	'VM_PRODUCT_SEARCHING' => 'Søker ...',
	'PHPSHOP_PRODUCT_FORM_ATTRIBUTE_LIST_EXAMPLES' => '<h4>Eksempler på variantlisteformat:</h4>
Tittel = Farge, Verdi = Rød ; Klikk på Ny verdi for å legge til ny farge: Grønn ; Klikk deretter Ny variant for å legge til ny variant.
<h4>Du kan justere prisen for hver enkelt variant ved hjelp av Avanserte varianter:</h4>
Pris = +10 for å legge dette beløpet til opprinnelig pris.<br />  Pris = -10 for å trekke dette beløpet fra opprinnelig pris.<br />  Pris = 10 for å sette prisen til dette beløpet.',
	'VM_FILES_FORM_PRODUCT_IMAGE' => 'Produktbilde (stort og miniatyr)',
	'VM_FILES_FORM_DOWNLOADABLE' => 'Nedlastbar produktfil (for salg)',
	'VM_FILES_FORM_RESIZE_IMAGE' => 'Endre størrelse på stort bilde?'
); $VM_LANG->initModule( 'product', $langvars );
?>
